name: aws-es-kibana # you probably want to 'snapcraft register <name>'
version: master # just for humans, typically '1.2+git' or '1.3.2'
summary: Proxy AWS Elasticsearch to local machine # 79 char long summary
description: |
  Please refer to https://github.com/santthosh/aws-es-kibana for original source.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  aws-es-kibana:
    command: aws-es-kibana
    plugs: [network, network-bind, home]

parts:
  aws-es-kibana:
    # See 'snapcraft plugins'
    plugin: nodejs
    node-engine: 6.10.3
    node-packages:
      - aws-es-kibana
